/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppTreeRouteImport } from './routes/_app.tree'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppImportRouteImport } from './routes/_app.import'
import { Route as AppHouseholdsRouteImport } from './routes/_app.households'
import { Route as AppDictionaryRouteImport } from './routes/_app.dictionary'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCorrectionsRouteImport } from './routes/_app.corrections'
import { Route as AppHouseholdsIdRouteImport } from './routes/_app.households.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTreeRoute = AppTreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppHouseholdsRoute = AppHouseholdsRouteImport.update({
  id: '/households',
  path: '/households',
  getParentRoute: () => AppRoute,
} as any)
const AppDictionaryRoute = AppDictionaryRouteImport.update({
  id: '/dictionary',
  path: '/dictionary',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCorrectionsRoute = AppCorrectionsRouteImport.update({
  id: '/corrections',
  path: '/corrections',
  getParentRoute: () => AppRoute,
} as any)
const AppHouseholdsIdRoute = AppHouseholdsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppHouseholdsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/corrections': typeof AppCorrectionsRoute
  '/dashboard': typeof AppDashboardRoute
  '/dictionary': typeof AppDictionaryRoute
  '/households': typeof AppHouseholdsRouteWithChildren
  '/import': typeof AppImportRoute
  '/reports': typeof AppReportsRoute
  '/tree': typeof AppTreeRoute
  '/users': typeof AppUsersRoute
  '/households/$id': typeof AppHouseholdsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/corrections': typeof AppCorrectionsRoute
  '/dashboard': typeof AppDashboardRoute
  '/dictionary': typeof AppDictionaryRoute
  '/households': typeof AppHouseholdsRouteWithChildren
  '/import': typeof AppImportRoute
  '/reports': typeof AppReportsRoute
  '/tree': typeof AppTreeRoute
  '/users': typeof AppUsersRoute
  '/households/$id': typeof AppHouseholdsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/corrections': typeof AppCorrectionsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/dictionary': typeof AppDictionaryRoute
  '/_app/households': typeof AppHouseholdsRouteWithChildren
  '/_app/import': typeof AppImportRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/tree': typeof AppTreeRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/households/$id': typeof AppHouseholdsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/corrections'
    | '/dashboard'
    | '/dictionary'
    | '/households'
    | '/import'
    | '/reports'
    | '/tree'
    | '/users'
    | '/households/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/corrections'
    | '/dashboard'
    | '/dictionary'
    | '/households'
    | '/import'
    | '/reports'
    | '/tree'
    | '/users'
    | '/households/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/corrections'
    | '/_app/dashboard'
    | '/_app/dictionary'
    | '/_app/households'
    | '/_app/import'
    | '/_app/reports'
    | '/_app/tree'
    | '/_app/users'
    | '/_app/households/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tree': {
      id: '/_app/tree'
      path: '/tree'
      fullPath: '/tree'
      preLoaderRoute: typeof AppTreeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/households': {
      id: '/_app/households'
      path: '/households'
      fullPath: '/households'
      preLoaderRoute: typeof AppHouseholdsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dictionary': {
      id: '/_app/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof AppDictionaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/corrections': {
      id: '/_app/corrections'
      path: '/corrections'
      fullPath: '/corrections'
      preLoaderRoute: typeof AppCorrectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/households/$id': {
      id: '/_app/households/$id'
      path: '/$id'
      fullPath: '/households/$id'
      preLoaderRoute: typeof AppHouseholdsIdRouteImport
      parentRoute: typeof AppHouseholdsRoute
    }
  }
}

interface AppHouseholdsRouteChildren {
  AppHouseholdsIdRoute: typeof AppHouseholdsIdRoute
}

const AppHouseholdsRouteChildren: AppHouseholdsRouteChildren = {
  AppHouseholdsIdRoute: AppHouseholdsIdRoute,
}

const AppHouseholdsRouteWithChildren = AppHouseholdsRoute._addFileChildren(
  AppHouseholdsRouteChildren,
)

interface AppRouteChildren {
  AppCorrectionsRoute: typeof AppCorrectionsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDictionaryRoute: typeof AppDictionaryRoute
  AppHouseholdsRoute: typeof AppHouseholdsRouteWithChildren
  AppImportRoute: typeof AppImportRoute
  AppReportsRoute: typeof AppReportsRoute
  AppTreeRoute: typeof AppTreeRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCorrectionsRoute: AppCorrectionsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDictionaryRoute: AppDictionaryRoute,
  AppHouseholdsRoute: AppHouseholdsRouteWithChildren,
  AppImportRoute: AppImportRoute,
  AppReportsRoute: AppReportsRoute,
  AppTreeRoute: AppTreeRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
